name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron:  '0 12 * * *'

jobs:
  linux:
    name: CI (Linux)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
        type: ["solc_upgrade", "linux", "solc"]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Install solc-select
      run: |
        sudo pip install .
        solc-select install all
    - name: Run Tests
      env:
        TEST_TYPE: ${{ matrix.type }}
      run: |
        bash scripts/test_${TEST_TYPE}.sh

  macos:
    name: CI (macOS)
    runs-on: macos-latest
    strategy:
      matrix:
        python:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
        type: ["solc_upgrade", "macos", "solc"]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Install solc-select
      run: |
        sudo pip install .
        solc-select install all
    - name: Run Tests
      env:
        TEST_TYPE: ${{ matrix.type }}
      run: |
        bash scripts/test_${TEST_TYPE}.sh

  windows:
    name: CI (Windows)
    runs-on: windows-2022
    strategy:
      matrix:
        python:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
        type: ["windows", "solc"]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Install solc-select
      run: |
        pip install . --user
        solc-select install all
    - name: Run Tests
      env:
        TEST_TYPE: ${{ matrix.type }}
      run: |
        bash scripts/test_${TEST_TYPE}.sh
      shell: bash
